// ============================================================
// MOCK DATA v3 — PR Tracker (IBS Heavy Industry)
// Cau truc phan anh dung file mau thuc te:
//   - Phan nhom vat tu: VTC / VPK / VDK
//   - Phan hang muc gia cong: INLET-U1 | SCR-U1 | BURNER-U1 | BOX1..N
//   - Vong doi hop dong: DOM + IMP
// Du an: 25-BRA-I-090 (BRADEN AIR COOLER) + 25-VPI-I-095 (BISON)
// ============================================================

import type {
  PRDetail,
  MaterialGroup,
  MaterialSubGroup,
  FabricationCategory,
  Project,
  PRHeader,
} from '@/types/procurement';

// ────────────────────────────────────────────────────────────
// MASTER: NHOM VAT TU (Material Groups)
// ────────────────────────────────────────────────────────────
export const MATERIAL_GROUPS: MaterialGroup[] = [
  {
    id: 'mg-vtc',
    code: 'VTC',
    name: 'Vat tu chinh',
    nameEn: 'Main Material',
    letter: 'A',
    sortOrder: 1,
  },
  {
    id: 'mg-vpk',
    code: 'VPK',
    name: 'Vat tu phu kien, bu long',
    nameEn: 'Accessory Material',
    letter: 'B',
    sortOrder: 2,
  },
  {
    id: 'mg-vdk',
    code: 'VDK',
    name: 'Vat tu dong kien',
    nameEn: 'Packing Material',
    letter: 'C',
    sortOrder: 3,
  },
  {
    id: 'mg-vbp',
    code: 'VBP',
    name: 'Vat tu lam bien phap',
    nameEn: 'Temporary Works',
    letter: 'D',
    sortOrder: 4,
  },
  {
    id: 'mg-vth',
    code: 'VTH',
    name: 'Vat tu tieu hao',
    nameEn: 'Consumables',
    letter: 'E',
    sortOrder: 5,
  },
  {
    id: 'mg-vts',
    code: 'VTS',
    name: 'Vat tu lam sach va son',
    nameEn: 'Surface Treatment',
    letter: 'F',
    sortOrder: 6,
  },
];

export const MATERIAL_SUBGROUPS: MaterialSubGroup[] = [
  // VTC — Vat tu chinh
  { id: 'sg-vtc01', groupId: 'mg-vtc', code: 'VTC01', name: 'Thep carbon cac loai', sortOrder: 1 },
  { id: 'sg-vtc02', groupId: 'mg-vtc', code: 'VTC02', name: 'Thep hop kim cac loai', sortOrder: 2 },
  { id: 'sg-vtc03', groupId: 'mg-vtc', code: 'VTC03', name: 'Tam san, grating', sortOrder: 3 },
  { id: 'sg-vtc04', groupId: 'mg-vtc', code: 'VTC04', name: 'Vat tu bao on', sortOrder: 4 },
  // VPK — Phu kien
  { id: 'sg-vpk01', groupId: 'mg-vpk', code: 'VPK01', name: 'Phu kien ket cau', sortOrder: 1 },
  {
    id: 'sg-vpk02',
    groupId: 'mg-vpk',
    code: 'VPK02',
    name: 'Bu long, ecu, vong dem',
    sortOrder: 2,
  },
  // VDK — Dong kien
  { id: 'sg-vdk01', groupId: 'mg-vdk', code: 'VDK01', name: 'Thep dong kien', sortOrder: 1 },
  { id: 'sg-vdk02', groupId: 'mg-vdk', code: 'VDK02', name: 'Phu kien dong kien', sortOrder: 2 },
  { id: 'sg-vdk03', groupId: 'mg-vdk', code: 'VDK03', name: 'Hang muc khac', sortOrder: 3 },
];

// ────────────────────────────────────────────────────────────
// HANG MUC GIA CONG — Du an I-090 (BRADEN AIR COOLER)
// ────────────────────────────────────────────────────────────
export const FAB_CATEGORIES_I090: FabricationCategory[] = [
  { id: 'fc-kctc', projectId: 'p002', code: 'KCTC', name: 'Ket cau thep chinh', sortOrder: 1 },
  { id: 'fc-kcdk', projectId: 'p002', code: 'KCDK', name: 'Ket cau dong kien', sortOrder: 2 },
  { id: 'fc-pk', projectId: 'p002', code: 'PK', name: 'Phu kien lien ket', sortOrder: 3 },
];

// HANG MUC GIA CONG — Du an I-095 (BISON / VOGT POWER)
export const FAB_CATEGORIES_I095: FabricationCategory[] = [
  { id: 'fc-inlet', projectId: 'p001', code: 'INLET-U1', name: 'Vat tu Inlet U1', sortOrder: 1 },
  { id: 'fc-scr', projectId: 'p001', code: 'SCR-U1', name: 'Vat tu SCR U1', sortOrder: 2 },
  { id: 'fc-burner', projectId: 'p001', code: 'BURNER-U1', name: 'Vat tu Burner U1', sortOrder: 3 },
  {
    id: 'fc-base',
    projectId: 'p001',
    code: 'BASE-PLATE',
    name: 'Base Plate + Stack Template',
    sortOrder: 4,
  },
  {
    id: 'fc-outlet',
    projectId: 'p001',
    code: 'OUTLET-DUCT',
    name: 'Vat tu Outlet Duct',
    sortOrder: 5,
  },
  { id: 'fc-topbeam', projectId: 'p001', code: 'TOP-BEAM', name: 'Vat tu Top Beam', sortOrder: 6 },
  { id: 'fc-box1', projectId: 'p001', code: 'BOX-1', name: 'Vat tu Box 1', sortOrder: 7 },
  { id: 'fc-box2', projectId: 'p001', code: 'BOX-2', name: 'Vat tu Box 2', sortOrder: 8 },
  { id: 'fc-stack', projectId: 'p001', code: 'STACK', name: 'Vat tu Stack', sortOrder: 9 },
  {
    id: 'fc-stair',
    projectId: 'p001',
    code: 'STAIR-TOWER',
    name: 'Vat tu Stair Tower',
    sortOrder: 10,
  },
];

// ────────────────────────────────────────────────────────────
// MOCK PR DATA — Mapping tu file mau thuc te
// ────────────────────────────────────────────────────────────
const BASE_PR = { prId: 'PR-I090-001', urgency: 'Normal' as const };

export const MOCK_PRS: PRDetail[] = [
  // ═══════════════════════════════════════════════════════════
  // A. VAT TU CHINH (VTC) — Thep den, Thep hinh, Phu kien chinh
  // ═══════════════════════════════════════════════════════════

  // ─── VTC01: Thep carbon (Ton tam / Plate Steel) ───────────
  {
    ...BASE_PR,
    id: 'I90-A1',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VPK01',
    materialSubGroupName: 'Phu kien ket cau',
    itemCode: 'I90-A1',
    itemName: 'Bulong mong',
    profile: 'ANCHOR BOLT M42',
    grade: 'N/A',
    uom: 'sets',
    unitWeight: 10.64,
    netQty: 320,
    netWeight: 3404,
    reqQty: 320,
    reqWeight: 3404,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 320,
    toBuyWeight: 3404,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 320,
        weight: 3404,
      },
    ],
    contracts: [
      {
        id: 'ct-A1-1',
        prDetailId: 'I90-A1',
        contractType: 'DOMESTIC',
        contractNo: '90.1/HDKT-2025/IBS-VSAN',
        vendorName: 'VSAN',
        actualProfile: 'Anchor Bolt M42 (Ecu M42-4.5, Vong dem phang M42)',
        contractQty: 320,
        contractWeight: 0,
        contractDate: '2025-04-26',
        unitPriceNoVAT: 635930,
        vatRate: 10,
        totalNoVAT: 203497600,
        totalWithVAT: 223847360,
        status: 'COMPLETED',
      },
    ],
    domesticTotalQty: 320,
    domesticTotalWeight: 0,
    domesticTotalNoVAT: 203497600,
    domesticTotalWithVAT: 223847360,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 320,
    totalPurchasedWeight: 0,
    diffQty: 0,
    diffWeight: 0,
    materialStatus: 'Đủ',
    statusFlag: 'Đã nhập kho',
    requiredDate: '2025-05-20',
    remarks: 'Thong so ky thuat theo ban ve dat hang I90-13105-ANCHOR BOLT M42',
  },

  {
    ...BASE_PR,
    id: 'I90-A2',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VTC01',
    materialSubGroupName: 'Thep carbon cac loai',
    itemCode: 'I90-A2',
    itemName: 'Ton tam',
    profile: 'PL10x2000x6000',
    grade: '1.0577(S355J2)/ASTM A36',
    uom: 'm2',
    unitWeight: 78.5,
    netQty: 0,
    netWeight: 0,
    reqQty: 48,
    reqWeight: 3768,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 48,
    toBuyWeight: 3768,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 30,
        weight: 2355,
      },
      {
        categoryId: 'fc-kcdk',
        categoryCode: 'KCDK',
        categoryName: 'Ket cau dong kien',
        qty: 18,
        weight: 1413,
      },
    ],
    contracts: [
      {
        id: 'ct-A2-1',
        prDetailId: 'I90-A2',
        contractType: 'DOMESTIC',
        contractNo: '150725/HN-IBS',
        vendorName: 'Hung Nguyen',
        actualProfile: 'Thep tam 10x2000x6000mm',
        contractQty: 48,
        contractWeight: 3768,
        contractDate: '2025-05-14',
        unitPriceNoVAT: 13090.91,
        vatRate: 10,
        totalNoVAT: 49274946,
        totalWithVAT: 54202440,
        status: 'COMPLETED',
      },
    ],
    domesticTotalQty: 48,
    domesticTotalWeight: 3768,
    domesticTotalNoVAT: 49274946,
    domesticTotalWithVAT: 54202440,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 48,
    totalPurchasedWeight: 3768,
    diffQty: 0,
    diffWeight: 0,
    materialStatus: 'Đủ',
    statusFlag: 'Đã nhập kho',
    requiredDate: '2025-05-17',
  },

  {
    ...BASE_PR,
    id: 'I90-A4',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VTC01',
    materialSubGroupName: 'Thep carbon cac loai',
    itemCode: 'I90-A4',
    itemName: 'Ton tam',
    profile: 'PL3x1500x6000',
    grade: 'ASTM A36',
    uom: 'm2',
    unitWeight: 23.6,
    netQty: 9.29,
    netWeight: 218.7,
    reqQty: 9,
    reqWeight: 212,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 9,
    toBuyWeight: 212,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 9,
        weight: 212,
      },
    ],
    contracts: [
      {
        id: 'ct-A4-1',
        prDetailId: 'I90-A4',
        contractType: 'DOMESTIC',
        contractNo: '150725/HN-IBS',
        vendorName: 'Hung Nguyen',
        actualProfile: 'Thep tam 3x1500x6000',
        actualGrade: 'A36',
        contractQty: 9,
        contractWeight: 211.95,
        contractDate: '2025-05-14',
        unitPriceNoVAT: 13090.91,
        vatRate: 10,
        totalNoVAT: 2774618,
        totalWithVAT: 3052080,
        status: 'COMPLETED',
      },
      {
        id: 'ct-A4-2',
        prDetailId: 'I90-A4',
        contractType: 'DOMESTIC',
        contractNo: 'I90-0409/HN-IBS',
        vendorName: 'Hung Nguyen',
        actualProfile: 'Thep tam 3x1500x6000 SS400',
        contractQty: 18,
        contractWeight: 423.9,
        contractDate: '2025-06-21',
        unitPriceNoVAT: 13090.91,
        vatRate: 10,
        totalNoVAT: 5549236,
        totalWithVAT: 6104160,
        status: 'COMPLETED',
      },
    ],
    domesticTotalQty: 1224,
    domesticTotalWeight: 28825,
    domesticTotalNoVAT: 0,
    domesticTotalWithVAT: 0,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 1224,
    totalPurchasedWeight: 28825,
    diffQty: 36,
    diffWeight: 1097,
    materialStatus: 'Thiếu',
    statusFlag: 'Đã nhập kho',
    requiredDate: '2025-05-17',
    remarks: 'Thieu - Thiet ke bao kho 2m chi mua 60 tam',
  },

  {
    ...BASE_PR,
    id: 'I90-A5',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VTC01',
    materialSubGroupName: 'Thep carbon cac loai',
    itemCode: 'I90-A5',
    itemName: 'Ton tam',
    profile: 'PL5x1500x6000',
    grade: 'ASTM A36',
    uom: 'm2',
    unitWeight: 39.3,
    netQty: 6.83,
    netWeight: 267.9,
    reqQty: 9,
    reqWeight: 353.3,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 9,
    toBuyWeight: 353.3,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 9,
        weight: 353.3,
      },
    ],
    contracts: [
      {
        id: 'ct-A5-1',
        prDetailId: 'I90-A5',
        contractType: 'DOMESTIC',
        contractNo: '210625/HN-IBS',
        vendorName: 'Hung Nguyen',
        actualProfile: 'Thep tam 5x1500x6000 (1 to)',
        contractQty: 9,
        contractWeight: 353.25,
        contractDate: '2025-06-21',
        unitPriceNoVAT: 13636,
        vatRate: 10,
        totalNoVAT: 0,
        totalWithVAT: 0,
        status: 'COMPLETED',
      },
    ],
    domesticTotalQty: 9,
    domesticTotalWeight: 353.3,
    domesticTotalNoVAT: 0,
    domesticTotalWithVAT: 0,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 9,
    totalPurchasedWeight: 353.3,
    diffQty: -3,
    diffWeight: 0,
    materialStatus: 'Thừa',
    statusFlag: 'Đã nhập kho',
  },

  {
    ...BASE_PR,
    id: 'I90-A12',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VTC01',
    materialSubGroupName: 'Thep carbon cac loai',
    itemCode: 'I90-A12',
    itemName: 'Ton tam',
    profile: 'PL10x1500x12000 / PL10x2000x12000',
    grade: 'ASTM A36',
    uom: 'm2',
    unitWeight: 78.5,
    netQty: 189.66,
    netWeight: 14888,
    reqQty: 198,
    reqWeight: 15543,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 198,
    toBuyWeight: 15543,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 150,
        weight: 11775,
      },
      {
        categoryId: 'fc-kcdk',
        categoryCode: 'KCDK',
        categoryName: 'Ket cau dong kien',
        qty: 48,
        weight: 3768,
      },
    ],
    contracts: [
      {
        id: 'ct-A12-1',
        prDetailId: 'I90-A12',
        contractType: 'DOMESTIC',
        contractNo: '210625/HN-IBS',
        vendorName: 'Hung Nguyen',
        actualProfile: 'Thep tam 10x2000x12000',
        contractQty: 288,
        contractWeight: 22608,
        contractDate: '2025-05-14',
        unitPriceNoVAT: 13090.91,
        vatRate: 10,
        totalNoVAT: 203472014,
        totalWithVAT: 223819215,
        status: 'COMPLETED',
      },
      {
        id: 'ct-A12-2',
        prDetailId: 'I90-A12',
        contractType: 'DOMESTIC',
        contractNo: '280725/HN-IBS',
        vendorName: 'Hung Nguyen',
        actualProfile: 'Thep tam 10x1500x12000 + 10x2000x12000',
        contractQty: 426,
        contractWeight: 33441,
        contractDate: '2025-07-28',
        unitPriceNoVAT: 13090.91,
        vatRate: 10,
        totalNoVAT: 0,
        totalWithVAT: 0,
        status: 'COMPLETED',
      },
    ],
    domesticTotalQty: 714,
    domesticTotalWeight: 56049,
    domesticTotalNoVAT: 203472014,
    domesticTotalWithVAT: 223819215,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 714,
    totalPurchasedWeight: 56049,
    diffQty: 0,
    diffWeight: 0,
    materialStatus: 'Đủ',
    statusFlag: 'Đã nhập kho',
    requiredDate: '2025-05-17',
  },

  // ─── VTC02: Thep hinh H / Thep hinh C ──────────────────────
  {
    ...BASE_PR,
    id: 'I90-C100',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VTC01',
    materialSubGroupName: 'Thep carbon cac loai',
    itemCode: 'I90-C100',
    itemName: 'Thep hinh-H',
    profile: 'HEA200(H190x200x6.5x10)-L12000',
    grade: 'SS400',
    uom: 'm',
    unitWeight: 0,
    netQty: 170,
    netWeight: 0,
    reqQty: 170,
    reqWeight: 0,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 170,
    toBuyWeight: 0,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 120,
        weight: 0,
      },
      {
        categoryId: 'fc-kcdk',
        categoryCode: 'KCDK',
        categoryName: 'Ket cau dong kien',
        qty: 50,
        weight: 0,
      },
    ],
    contracts: [
      {
        id: 'ct-C100-1',
        prDetailId: 'I90-C100',
        contractType: 'DOMESTIC',
        contractNo: 'I90-0809/HN-IBS',
        vendorName: 'Hung Nguyen',
        actualProfile: 'Thep H200x200x8x12x12000 = 1 Cay',
        contractQty: 170,
        contractWeight: 0,
        contractDate: '2025-08-09',
        unitPriceNoVAT: 17545,
        vatRate: 10,
        totalNoVAT: 156776769,
        totalWithVAT: 0,
        status: 'COMPLETED',
        notes: 'Gia tri mua dang vuot du toan - Giai trinh BOD',
      },
    ],
    domesticTotalQty: 170,
    domesticTotalWeight: 0,
    domesticTotalNoVAT: 156776769,
    domesticTotalWithVAT: 0,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 170,
    totalPurchasedWeight: 0,
    diffQty: 0,
    diffWeight: 0,
    materialStatus: 'Đủ',
    statusFlag: 'Đã nhập kho',
    remarks: 'Gia tri mua vuot du toan. Da giai trinh BOD.',
  },

  // ─── Co nhap khau (IMPORT) ─────────────────────────────────
  {
    ...BASE_PR,
    id: 'I90-C21',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VTC01',
    materialSubGroupName: 'Thep carbon cac loai',
    itemCode: 'I90-C21',
    itemName: 'Thep hinh-C',
    profile: 'UNP200(C200x75x8.5x11.5)-L12000',
    grade: '1.0038/A36',
    uom: 'm',
    unitWeight: 0,
    netQty: 84,
    netWeight: 0,
    reqQty: 84,
    reqWeight: 0,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 84,
    toBuyWeight: 0,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 60,
        weight: 0,
      },
      {
        categoryId: 'fc-kcdk',
        categoryCode: 'KCDK',
        categoryName: 'Ket cau dong kien',
        qty: 24,
        weight: 0,
      },
    ],
    contracts: [
      {
        id: 'ct-C21-dom',
        prDetailId: 'I90-C21',
        contractType: 'DOMESTIC',
        contractNo: '090925/NH-IBS',
        vendorName: 'Ngoc Hieu',
        actualProfile: 'Thep U200x90x8x13.5x12000',
        contractQty: 42,
        contractWeight: 0,
        contractDate: '2025-09-09',
        unitPriceNoVAT: 17500,
        vatRate: 10,
        totalNoVAT: 0,
        totalWithVAT: 0,
        status: 'COMPLETED',
      },
      {
        id: 'ct-C21-imp',
        prDetailId: 'I90-C21',
        contractType: 'IMPORT',
        contractNo: 'I90-0310/HN-IBS-IMP',
        vendorName: 'Hung Nguyen',
        actualProfile: 'Thep U200x90x8x13.5x12000 (7 cay)',
        contractQty: 42,
        contractWeight: 0,
        contractDate: '2025-10-03',
        importLCDate: '2025-09-25',
        exportPort: 'Busan (Han Quoc)',
        cifDate: '2025-11-10',
        arrivedDate: '2025-11-15',
        handoverDate: '2025-11-20',
        unitPriceNoVAT: 18000,
        vatRate: 10,
        totalNoVAT: 0,
        totalWithVAT: 0,
        status: 'COMPLETED',
      },
    ],
    domesticTotalQty: 42,
    domesticTotalWeight: 0,
    domesticTotalNoVAT: 0,
    domesticTotalWithVAT: 0,
    importTotalQty: 42,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 84,
    totalPurchasedWeight: 0,
    diffQty: 0,
    diffWeight: 0,
    materialStatus: 'Đủ',
    statusFlag: 'Đã nhập kho',
  },

  // ═══════════════════════════════════════════════════════════
  // B. VAT TU PHU KIEN (VPK) — Bu long, ecu, vong dem
  // ═══════════════════════════════════════════════════════════
  {
    ...BASE_PR,
    id: 'I90-C44',
    materialGroupCode: 'VPK',
    materialGroupName: 'Vat tu phu kien, bu long',
    materialSubGroupCode: 'VPK02',
    materialSubGroupName: 'Bu long, ecu, vong dem',
    itemCode: 'I90-C44',
    itemName: 'Bu long',
    profile: 'Bolt-M20x60-ISO4017-8.8-Galv',
    grade: 'Grade 8.8',
    uom: 'pcs',
    unitWeight: 0,
    netQty: 960,
    netWeight: 0,
    reqQty: 960,
    reqWeight: 0,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 960,
    toBuyWeight: 0,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 640,
        weight: 0,
      },
      {
        categoryId: 'fc-kcdk',
        categoryCode: 'KCDK',
        categoryName: 'Ket cau dong kien',
        qty: 320,
        weight: 0,
      },
    ],
    contracts: [
      {
        id: 'ct-C44-1',
        prDetailId: 'I90-C44',
        contractType: 'DOMESTIC',
        contractNo: '90.15/HDKT-2025/IBS-VSAN',
        vendorName: 'VSAN',
        actualProfile: 'Bolt-M20x60-ISO4017-8.8-Galv',
        contractQty: 960,
        contractWeight: 0,
        contractDate: '2025-09-16',
        unitPriceNoVAT: 4190,
        vatRate: 10,
        totalNoVAT: 0,
        totalWithVAT: 0,
        status: 'COMPLETED',
      },
    ],
    domesticTotalQty: 960,
    domesticTotalWeight: 0,
    domesticTotalNoVAT: 0,
    domesticTotalWithVAT: 0,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 960,
    totalPurchasedWeight: 0,
    diffQty: 0,
    diffWeight: 0,
    materialStatus: 'Đủ',
    statusFlag: 'Đã nhập kho',
  },

  {
    ...BASE_PR,
    id: 'I90-C68',
    materialGroupCode: 'VPK',
    materialGroupName: 'Vat tu phu kien, bu long',
    materialSubGroupCode: 'VPK02',
    materialSubGroupName: 'Bu long, ecu, vong dem',
    itemCode: 'I90-C68',
    itemName: 'Dem',
    profile: 'Washer-M20-ISO7089-St-200HV-Galv',
    grade: 'Grade 200HV',
    uom: 'pcs',
    unitWeight: 0,
    netQty: 2080,
    netWeight: 0,
    reqQty: 2080,
    reqWeight: 0,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 2080,
    toBuyWeight: 0,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 1600,
        weight: 0,
      },
      {
        categoryId: 'fc-kcdk',
        categoryCode: 'KCDK',
        categoryName: 'Ket cau dong kien',
        qty: 480,
        weight: 0,
      },
    ],
    contracts: [
      {
        id: 'ct-C68-1',
        prDetailId: 'I90-C68',
        contractType: 'DOMESTIC',
        contractNo: '90.15/HDKT-2025/IBS-VSAN',
        vendorName: 'VSAN',
        actualProfile: 'Washer-M20-ISO7089-St-200HV-Galv',
        contractQty: 2080,
        contractWeight: 0,
        contractDate: '2025-09-16',
        unitPriceNoVAT: 1200,
        vatRate: 10,
        totalNoVAT: 0,
        totalWithVAT: 0,
        status: 'COMPLETED',
      },
    ],
    domesticTotalQty: 2080,
    domesticTotalWeight: 0,
    domesticTotalNoVAT: 0,
    domesticTotalWithVAT: 0,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 2080,
    totalPurchasedWeight: 0,
    diffQty: 0,
    diffWeight: 0,
    materialStatus: 'Đủ',
    statusFlag: 'Đã nhập kho',
  },

  // ═══════════════════════════════════════════════════════════
  // C. VAT TU DONG KIEN (VDK) — Thung go, thep dong kien
  // ═══════════════════════════════════════════════════════════
  {
    ...BASE_PR,
    id: 'I90-C1',
    materialGroupCode: 'VDK',
    materialGroupName: 'Vat tu dong kien',
    materialSubGroupCode: 'VDK03',
    materialSubGroupName: 'Hang muc khac',
    itemCode: 'I90-C1',
    itemName: 'Thung go',
    profile: 'Thung go co dau khu trung ISPM-15',
    grade: 'N/A',
    uom: 'sets',
    unitWeight: 0,
    netQty: 12,
    netWeight: 0,
    reqQty: 12,
    reqWeight: 0,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 12,
    toBuyWeight: 0,
    fabAllocations: [
      {
        categoryId: 'fc-kcdk',
        categoryCode: 'KCDK',
        categoryName: 'Ket cau dong kien',
        qty: 12,
        weight: 0,
      },
    ],
    contracts: [
      {
        id: 'ct-C1-1',
        prDetailId: 'I90-C1',
        contractType: 'DOMESTIC',
        contractNo: 'THUNG-090-2025',
        vendorName: 'Cong ty Bao Bi Hai Phong',
        actualProfile: 'Thung go khung kim loai, co dau khu trung',
        contractQty: 12,
        contractWeight: 0,
        contractDate: '2025-11-01',
        unitPriceNoVAT: 4500000,
        vatRate: 10,
        totalNoVAT: 54000000,
        totalWithVAT: 59400000,
        status: 'ACTIVE',
      },
    ],
    domesticTotalQty: 12,
    domesticTotalWeight: 0,
    domesticTotalNoVAT: 54000000,
    domesticTotalWithVAT: 59400000,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 12,
    totalPurchasedWeight: 0,
    diffQty: 0,
    diffWeight: 0,
    materialStatus: 'Đủ',
    statusFlag: 'Chờ báo giá',
    remarks: 'Can kiem tra: Go co dau khu trung ISPM-15 theo yeu cau xuat khau',
  },

  // ═══════════════════════════════════════════════════════════
  // VAT TU DANG DAM PHAN / CHO BAO GIA
  // ═══════════════════════════════════════════════════════════
  {
    ...BASE_PR,
    id: 'I90-D001',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VTC01',
    materialSubGroupName: 'Thep carbon cac loai',
    itemCode: 'I90-D001',
    itemName: 'Ton tam',
    profile: 'PL40x2000x12000',
    grade: 'ASTM A36',
    uom: 'm2',
    unitWeight: 314,
    netQty: 24,
    netWeight: 7536,
    reqQty: 24,
    reqWeight: 7536,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 24,
    toBuyWeight: 7536,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 24,
        weight: 7536,
      },
    ],
    contracts: [],
    domesticTotalQty: 0,
    domesticTotalWeight: 0,
    domesticTotalNoVAT: 0,
    domesticTotalWithVAT: 0,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 0,
    totalPurchasedWeight: 0,
    diffQty: -24,
    diffWeight: -7536,
    materialStatus: 'Thiếu',
    statusFlag: 'Đang đàm phán',
    requiredDate: '2026-05-15',
    urgency: 'Urgent',
  },

  {
    ...BASE_PR,
    id: 'I90-D002',
    materialGroupCode: 'VTC',
    materialGroupName: 'Vat tu chinh',
    materialSubGroupCode: 'VTC02',
    materialSubGroupName: 'Thep hop kim cac loai',
    itemCode: 'I90-D002',
    itemName: 'Thep hop kim tam',
    profile: 'PL12x2000x6000',
    grade: 'ASTM A516 Gr.70',
    uom: 'm2',
    unitWeight: 94.2,
    netQty: 48,
    netWeight: 4522,
    reqQty: 48,
    reqWeight: 4522,
    remainQty: 0,
    remainWeight: 0,
    toBuyQty: 48,
    toBuyWeight: 4522,
    fabAllocations: [
      {
        categoryId: 'fc-kctc',
        categoryCode: 'KCTC',
        categoryName: 'Ket cau thep chinh',
        qty: 48,
        weight: 4522,
      },
    ],
    contracts: [],
    domesticTotalQty: 0,
    domesticTotalWeight: 0,
    domesticTotalNoVAT: 0,
    domesticTotalWithVAT: 0,
    importTotalQty: 0,
    importTotalWeight: 0,
    importTotalNoVAT: 0,
    importCIFTotal: 0,
    totalPurchasedQty: 0,
    totalPurchasedWeight: 0,
    diffQty: -48,
    diffWeight: -4522,
    materialStatus: 'Thiếu',
    statusFlag: 'Chờ báo giá',
    requiredDate: '2026-06-01',
    urgency: 'Critical',
    remarks: 'Thep hop kim A516 Gr.70 - can kiem tra chung chi vat lieu (MTR)',
  },
];
